services:
  perses:
    image: persesdev/perses:v0.53-distroless-debug
    container_name: perses
    command: "--config=/etc/perses/config/config.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./perses/config.yaml:/etc/perses/config/config.yaml
      - ./perses/datasource.yaml:/etc/perses/resources/datasource.yaml
      - ./perses/project.yaml:/etc/perses/resources/project.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules/prometheus/blackbox-exporter:/etc/prometheus/rules
      - prometheus_data:/prometheus
    depends_on:
      - blackbox-exporter

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    ports:
      - "9115:9115"
    restart: unless-stopped
    volumes:
      - ./prometheus/blackbox.yml:/etc/blackbox/blackbox.yml

volumes:
  prometheus_data: